[package]
name = "shazam"
version = "1.0.0"
edition = "2021"

[lib]
name = "shazam"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.1", features = ["extension-module"] }
chfft = "0.3.4"
rodio = "0.13.1"
byteorder = "1.3.4"
crc32fast = "1.2.0"
base64 = "0.12.3"
tempfile = "3.2.0"
